# 工作流的名称
name: 菜玩网自动签到

于:
  # 触发工作流的事件
  schedule:
    # cron 表达式，用于定时执行。'05 16 * * *' 表示在每天的 UTC 时间 16:05 执行。
    # 这对应北京时间 (UTC+8) 的凌晨 00:05，是签到的好时机。
    - cron: '05 16 * * *'
  
  workflow_dispatch:
    # 这允许你手动点击 "Run workflow" 按钮来触发此工作流，方便测试。

jobs:
  # 定义一个名为 'checkin' 的任务
  checkin:
    # 指定任务运行的虚拟环境
    runs-on: ubuntu-latest

    # 任务执行的步骤
    steps:
      # 第一步：检出你的仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 第二步：设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # 可以指定你需要的 Python 版本

      # 第三步：安装脚本所需的依赖库
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install httpx

      # 第四步：运行签到脚本
      - name: Run check-in script
        env:
          # 在这里，我们将 GitHub Secret 注入到脚本的环境变量中
          CAIWAN_COOKIE: ${{ secrets.CAIWAN_COOKIE }}
        run: python checkin.py
