name: 菜玩网自动签到 (提前30分钟方案)

on:
  schedule:
    # 使用 cron 表达式定时。'30 15 * * *' 表示在每天的 UTC 时间 15:30 启动。
    # 这对应北京时间 (UTC+8) 的 23:30，目的是提前半小时启动。
    - cron: '30 16 * * *'
  
  workflow_dispatch:
    # 保留此项，以便你可以随时手动触发进行测试。

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install httpx

      - name: Run check-in script
        env:
          CAIWAN_COOKIE: ${{ secrets.CAIWAN_COOKIE }}
        run: python checkin.py
